// Erzeugt, nicht von Hand aendern.
//
// Gedenktext "ueber die Katze". Unantastbar: wortwoertlich aus mega-raw
// uebernommen (cat_text.h, catTextDe).
#pragma once

static const char kKatzeText[] = "Ich habe mich fuer meine Katze als Programmlogo entschieden. Die folgenden Zeilen sind ihr gewidmet — eine kleine Hommage und ein Gedenken.\n\nJede dritte Katze ab einem Alter von 10–12 Jahren leidet an CNI (chronischer Niereninsuffizienz). Leider wird die Krankheit oft erst sichtbar, wenn sie sich bereits dem Endstadium zuneigt. Viele Aerzte weisen nicht darauf hin.\n\nFuehlen Sie sich also nicht sicher, nur weil Sie regelmaessig und verantwortungsvoll zum Tierarzt gehen und dieser sagt, es sei alles in Ordnung. Bitte verlangen Sie regelmaessig einen Bluttest. Nur dieser kann die Katze retten und ihr Leben nachweislich wertvoll verlaengern. Frueherkennung macht den Unterschied.\n\nMein Kater bekam Anfang 2025 die Diagnose, nachdem es Auffaelligkeiten in seinem Verhalten gab: mehr Durst, der Drang, ungewoehnliche Wasserquellen aufzusuchen. Wir entschieden uns fuer eine Behandlung in einer Tierklinik, und waehrend dieser Zeit haben ihn sich gleich mehrere Aerzte angeschaut — und jeder war anderer Meinung. Es ist wichtig, auch Ihren eigenen Sinnen zu trauen, da Sie Ihre Katze am besten kennen.\n\nAm 11. Juni 2025 ist er gestorben.\n\nDie Katze in der Software ist ein Pixel-Portrait zur Erinnerung an meinen Kater, abgeleitet von einem echten Foto aus dem Jahr 2010 — als wir ihn aus dem Tierheim holten.\n\nAuch wenn dieses Projekt einen Spenden-Button hat: Die groesste Freude, die Sie mir machen koennen, ist, Ihre Katze auf diese Krankheit untersuchen zu lassen.\n\n* CNI betrifft nicht nur Katzen, sondern auch andere Tiere.\n\nUnd wenn das jetzt auch nur einer macht, hat dieser Text seinen Sinn und Zweck in einer Software, die damit eigentlich gar nichts zu tun hat, schon vollends erfuellt.\n\nIch danke euch fuers Lesen.\n\nIn memory of Jason — 2010–2025.";

// Englische Fassung, ebenso wortwoertlich (catTextEn).
static const char kKatzeTextEn[] = "I chose my cat as the program's logo. The following lines are dedicated to her — a small homage and a remembrance.\n\nOne in three cats aged 10–12 or older suffers from CKD (chronic kidney disease). Sadly, the illness often only becomes visible once it is already nearing its final stage. Many vets don't point this out.\n\nSo don't feel safe just because you take your cat to the vet regularly and responsibly and they tell you everything is fine. Please ask for a blood test regularly. Only that can save your cat and measurably extend its life in a meaningful way. Early detection makes the difference.\n\nMy cat was diagnosed in early 2025, after changes in his behaviour: more thirst, the urge to seek out unusual sources of water. We decided on treatment at an animal clinic, and during that time several vets examined him — and each had a different opinion. It is important to trust your own senses too, because you know your cat best.\n\nHe passed away on June 11, 2025.\n\nThe cat in the software is a pixel portrait in memory of my cat, derived from a real photo from 2010 — when we brought him home from the shelter.\n\nEven though this project has a donation button: the greatest gift you can give me is to have your own cat checked for this illness.\n\n* CKD does not only affect cats, but other animals too.\n\nAnd if even just one person does this, then this text has fully served its purpose — in a piece of software that actually has nothing to do with it.\n\nThank you for reading.\n\nIn memory of Jason — 2010–2025.";
